/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access + refresh token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the access token using a refresh token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin / L&D dashboard summary */
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/maverick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Maverick (learner) dashboard summary */
        get: operations["getMaverickDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/supervisor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supervisor dashboard summary */
        get: operations["getSupervisorDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{cycleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        /** Load the form bundle (cycle context + the caller's draft) */
        get: operations["getFeedbackForm"];
        /** Autosave a partial draft (idempotent; replaces the caller's draft fields) */
        put: operations["autosaveFeedback"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications for the current user */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a notification as Read */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent reports the Admin has triggered */
        get: operations["listReports"];
        put?: never;
        /** Trigger a new report export. Admin only. */
        post: operations["triggerReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the assistant a question. Stateless — the client sends the whole
         *     conversation each turn. The reply is always tagged with an AiBadge;
         *     when degraded=true the response came from the .NET StubAiService
         *     (rule-based) and the UI labels it subtly.
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/effectiveness/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supervisor's queue of pending effectiveness evaluations */
        get: operations["listPendingEffectiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/effectiveness/{cycleId}/{maverickId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
                maverickId: string;
            };
            cookie?: never;
        };
        /** Load the effectiveness form bundle for a (cycle, maverick) pair */
        get: operations["getEffectivenessForm"];
        /** Autosave a partial draft (idempotent) */
        put: operations["autosaveEffectiveness"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/effectiveness/{cycleId}/{maverickId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
                maverickId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize the effectiveness response. */
        post: operations["submitEffectiveness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feedback cycles (paginated, filterable) */
        get: operations["listCycles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycles/{cycleId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a cycle. Returns 409 if completion is below threshold. */
        post: operations["closeCycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycles/{cycleId}/override-close": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin-only override-close. Bypasses the threshold and writes an
         *     AuditLog row server-side. Reason is mandatory.
         */
        post: operations["overrideCloseCycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trainers with aggregate stats (Admin only) */
        get: operations["listTrainers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainers/{trainerId}/scorecard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainerId: string;
            };
            cookie?: never;
        };
        /** Per-trainer scorecard (Admin only) */
        get: operations["getTrainerScorecard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (Admin only) */
        get: operations["listPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Maverick's own feedback history (all roles) */
        get: operations["listFeedbackHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{cycleId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize the draft. All required fields must be present. */
        post: operations["submitFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem+json */
        Problem: {
            /**
             * Format: uri
             * @example about:blank
             */
            type: string;
            /** @example Unauthorized */
            title: string;
            /** @example 401 */
            status: number;
            /** @example Invalid credentials */
            detail?: string;
            /** @example 01HF3K2P3QYG1B6Y4W5Z6V7X8Y */
            traceId: string;
        };
        /** @enum {string} */
        Role: "Admin" | "Maverick" | "Supervisor";
        User: {
            /**
             * Format: uuid
             * @description UUID v7
             */
            id: string;
            /** Format: email */
            email: string;
            fullName: string;
            role: components["schemas"]["Role"];
            employeeCode?: string | null;
            /** Format: uuid */
            managerId?: string | null;
            isActive: boolean;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthSession: {
            accessToken: string;
            refreshToken: string;
            /** @description Seconds until the access token expires */
            expiresInSeconds: number;
            user: components["schemas"]["User"];
        };
        /** @description Stamp on any AI-derived value. degraded=true means the stub or a fallback produced it; UI must label it subtly. */
        AiBadge: {
            aiGenerated: boolean;
            degraded: boolean;
            /** Format: date-time */
            generatedAt?: string;
            /** @description How many responses contributed to this value */
            sourceCount?: number;
        };
        Trend: {
            /** @enum {string} */
            direction: "up" | "down" | "flat";
            /** @description Percent change vs the prior period */
            deltaPct: number;
        };
        MetricCard: {
            key: string;
            label: string;
            /** @description Pre-formatted display value (e.g. "82%", "4.2/5") */
            value: string;
            helper?: string | null;
            trend?: components["schemas"]["Trend"];
        };
        SentimentBreakdown: {
            positive: number;
            neutral: number;
            negative: number;
            ai: components["schemas"]["AiBadge"];
        };
        TrainerScorecardRow: {
            /** Format: uuid */
            trainerId: string;
            name: string;
            organization?: string | null;
            courses: number;
            sessions: number;
            avgRating: number;
            completionRate: number;
        };
        Alert: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            severity: "info" | "warn" | "alert";
            title: string;
            body?: string | null;
            /** Format: uuid */
            cycleId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AiInsightBanner: {
            /** @description One-paragraph natural language insight */
            summary: string;
            topThemes?: string[];
            ai: components["schemas"]["AiBadge"];
        };
        AdminDashboard: {
            metrics: components["schemas"]["MetricCard"][];
            sentiment: components["schemas"]["SentimentBreakdown"];
            trainers: components["schemas"]["TrainerScorecardRow"][];
            alerts: components["schemas"]["Alert"][];
            insight: components["schemas"]["AiInsightBanner"];
        };
        PendingFeedbackItem: {
            /** Format: uuid */
            cycleId: string;
            courseName: string;
            trainerName?: string | null;
            /** Format: date-time */
            sessionEndedAt?: string | null;
            /** Format: date-time */
            dueAt: string;
            /** @enum {string} */
            status: "NotStarted" | "Draft" | "Submitted";
        };
        MaverickDashboard: {
            pending: components["schemas"]["PendingFeedbackItem"][];
            completed: components["schemas"]["PendingFeedbackItem"][];
            streak: {
                submittedCount: number;
                onTimeRate: number;
            };
        };
        SupervisorTeamRow: {
            /** Format: uuid */
            maverickId: string;
            maverickName: string;
            pendingCount: number;
            /** Format: date-time */
            lastSubmittedAt: string | null;
        };
        SupervisorDashboard: {
            pendingEvaluations: number;
            team: components["schemas"]["SupervisorTeamRow"][];
            metrics: components["schemas"]["MetricCard"][];
        };
        /** @description Snapshot the Maverick sees while answering — read-only on the client. */
        FeedbackCycleContext: {
            /** Format: uuid */
            cycleId: string;
            courseName: string;
            trainerName?: string | null;
            /** Format: date-time */
            sessionEndedAt?: string | null;
            /** Format: date-time */
            dueAt: string;
            /** @enum {string} */
            status: "Open" | "Closed" | "OverrideClosed";
        };
        FeedbackDraft: {
            /** Format: uuid */
            cycleId: string;
            overallRating?: number | null;
            highlights?: string | null;
            improvements?: string | null;
            /** @enum {string} */
            status: "Draft" | "Submitted";
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            submittedAt?: string | null;
        };
        /**
         * @description Partial autosave body. Any present field replaces the stored value.
         *     Omitted fields are untouched. PUT is idempotent — re-sending the same
         *     body is safe and returns the same draft.
         */
        FeedbackDraftPatch: {
            overallRating?: number | null;
            highlights?: string | null;
            improvements?: string | null;
        };
        /** @description Strict shape for the finalize call. All required fields must be present. */
        FeedbackSubmit: {
            overallRating: number;
            highlights: string;
            improvements: string;
        };
        FeedbackFormBundle: {
            cycle: components["schemas"]["FeedbackCycleContext"];
            draft: components["schemas"]["FeedbackDraft"];
        };
        /** @enum {string} */
        CycleType: "MaverickPostTraining" | "SupervisorEffectiveness";
        /** @enum {string} */
        CycleStatus: "Open" | "Closed" | "OverrideClosed";
        /** @enum {string} */
        TriggerBasis: "TrainingCompletion" | "Post3MonthProject";
        Cycle: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            courseName: string;
            trainerName?: string | null;
            type: components["schemas"]["CycleType"];
            status: components["schemas"]["CycleStatus"];
            /**
             * @description Minimum completion (0..1) required to close without override.
             * @example 0.78
             */
            threshold: number;
            /** Format: date-time */
            opensAt: string;
            /** Format: date-time */
            closesAt?: string | null;
            /** @description Total Mavericks (or supervisors) expected to respond. */
            expectedCount: number;
            responseCount: number;
            /** @description responseCount / expectedCount, server-computed (0..1). */
            completionRate: number;
            triggerBasis: components["schemas"]["TriggerBasis"];
            /** Format: date-time */
            closedAt?: string | null;
            closedByName?: string | null;
            /** @description Present iff status=OverrideClosed. */
            overrideReason?: string | null;
        };
        CyclePage: {
            data: components["schemas"]["Cycle"][];
            page: number;
            pageSize: number;
            total: number;
        };
        OverrideCloseRequest: {
            /** @description Justification recorded in the AuditLog. */
            reason: string;
        };
        /**
         * @description 409 returned when POST /cycles/{id}/close is called while completion
         *     is below the configured threshold. Extends RFC 9457 Problem with
         *     machine-readable rates so the UI can render the gap.
         */
        ProblemBelowThreshold: components["schemas"]["Problem"] & {
            currentRate: number;
            requiredRate: number;
            /** Format: uuid */
            cycleId: string;
        };
        EffectivenessCycleContext: {
            /** Format: uuid */
            cycleId: string;
            courseName: string;
            trainerName?: string | null;
            /** Format: date-time */
            dueAt: string;
            status: components["schemas"]["CycleStatus"];
        };
        /** @description Read-only snapshot of the Maverick being evaluated. */
        EffectivenessMaverickContext: {
            /** Format: uuid */
            id: string;
            fullName: string;
            employeeCode: string | null;
            /** Format: date-time */
            sessionEndedAt?: string | null;
            /** @description Maverick's own post-training rating for this course (1..5) if available. */
            avgPostTrainingRating?: number | null;
        };
        EffectivenessDraft: {
            /** Format: uuid */
            cycleId: string;
            /** Format: uuid */
            maverickId: string;
            technicalCompetency?: number | null;
            softSkills?: number | null;
            projectPerformance?: number | null;
            overallReadiness?: number | null;
            comments?: string | null;
            futureTrainingRecommendations?: string | null;
            /** @enum {string} */
            status: "Draft" | "Submitted";
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            submittedAt?: string | null;
        };
        /**
         * @description Partial autosave body. Any present field replaces the stored value.
         *     PUT is idempotent — re-sending the same body is safe.
         */
        EffectivenessDraftPatch: {
            technicalCompetency?: number | null;
            softSkills?: number | null;
            projectPerformance?: number | null;
            overallReadiness?: number | null;
            comments?: string | null;
            futureTrainingRecommendations?: string | null;
        };
        /** @description Strict shape for the finalize call. All four ratings + comments required. */
        EffectivenessSubmit: {
            technicalCompetency: number;
            softSkills: number;
            projectPerformance: number;
            overallReadiness: number;
            comments: string;
            futureTrainingRecommendations?: string | null;
        };
        EffectivenessFormBundle: {
            cycle: components["schemas"]["EffectivenessCycleContext"];
            maverick: components["schemas"]["EffectivenessMaverickContext"];
            draft: components["schemas"]["EffectivenessDraft"];
        };
        EffectivenessPendingItem: {
            /** Format: uuid */
            cycleId: string;
            /** Format: uuid */
            maverickId: string;
            maverickName: string;
            courseName: string;
            trainerName?: string | null;
            /** Format: date-time */
            dueAt: string;
            /** @enum {string} */
            status: "NotStarted" | "Draft" | "Submitted";
            /** Format: date-time */
            submittedAt?: string | null;
        };
        EffectivenessQueue: {
            pending: components["schemas"]["EffectivenessPendingItem"][];
            recentlySubmitted: components["schemas"]["EffectivenessPendingItem"][];
        };
        ChatMessage: {
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
        };
        /** @description Page the user is on. Lets the assistant tailor its reply. */
        ChatContext: {
            route?: string | null;
        };
        ChatRequest: {
            messages: components["schemas"]["ChatMessage"][];
            context?: components["schemas"]["ChatContext"];
        };
        /** @description One row in an optional structured payload (e.g. a list of cycles or feedback items). */
        ChatDataItem: {
            label: string;
            sublabel?: string | null;
            /** @description Internal app path the UI can link to. */
            href?: string | null;
        };
        ChatData: {
            /**
             * @description Hint for how to render the payload. Initially "list"; future
             *     variants ("table", "chart") will extend this without breaking
             *     old clients.
             */
            kind: string;
            title?: string | null;
            items: components["schemas"]["ChatDataItem"][];
        };
        ChatReply: {
            /** Format: uuid */
            id: string;
            message: components["schemas"]["ChatMessage"];
            /** @description Suggested follow-up prompts. */
            suggestions?: string[];
            data?: components["schemas"]["ChatData"];
            ai: components["schemas"]["AiBadge"];
        };
        /** @enum {string} */
        NotificationChannel: "Email" | "SMS" | "Portal";
        /** @enum {string} */
        NotificationStatus: "Queued" | "Sent" | "Failed" | "Read";
        /**
         * @description UI tone hint. Independent of delivery status.
         * @enum {string}
         */
        NotificationSeverity: "info" | "warn" | "alert";
        Notification: {
            /** Format: uuid */
            id: string;
            channel: components["schemas"]["NotificationChannel"];
            subject: string;
            body?: string | null;
            status: components["schemas"]["NotificationStatus"];
            severity: components["schemas"]["NotificationSeverity"];
            /** Format: uuid */
            relatedCycleId?: string | null;
            /** @description Internal path the UI links the notification to. */
            href?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            sentAt?: string | null;
            /** Format: date-time */
            readAt?: string | null;
        };
        NotificationListResponse: {
            data: components["schemas"]["Notification"][];
            unreadCount: number;
        };
        /** @enum {string} */
        ReportFormat: "Xlsx" | "Csv" | "Pdf";
        /** @enum {string} */
        ReportScope: "Cycles" | "Trainers" | "Sentiment";
        /** @enum {string} */
        ReportStatus: "Queued" | "Running" | "Ready" | "Failed";
        ReportRequest: {
            scope: components["schemas"]["ReportScope"];
            format: components["schemas"]["ReportFormat"];
            cycleStatus?: components["schemas"]["CycleStatus"];
            /** Format: date */
            dateFrom?: string | null;
            /** Format: date */
            dateTo?: string | null;
        };
        Report: {
            /** Format: uuid */
            id: string;
            scope: components["schemas"]["ReportScope"];
            format: components["schemas"]["ReportFormat"];
            status: components["schemas"]["ReportStatus"];
            cycleStatus?: components["schemas"]["CycleStatus"];
            /** Format: date */
            dateFrom?: string | null;
            /** Format: date */
            dateTo?: string | null;
            /** @description Internal path or signed URL. Only set when status=Ready. */
            downloadUrl?: string | null;
            rowCount?: number | null;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            requestedByName: string;
        };
        /** @enum {string} */
        TrainerEngagementType: "Internal" | "External";
        TrainerListRow: {
            /** Format: uuid */
            trainerId: string;
            name: string;
            organization?: string | null;
            engagementType: components["schemas"]["TrainerEngagementType"];
            domain: string;
            courses: number;
            sessions: number;
            avgRating: number;
            completionRate: number;
        };
        TrainerPage: {
            data: components["schemas"]["TrainerListRow"][];
            page: number;
            pageSize: number;
            total: number;
        };
        TrainerScorecardCycle: {
            /** Format: uuid */
            cycleId: string;
            courseName: string;
            completionRate: number;
            /** @description Mean overall rating across submitted responses, null if no responses yet. */
            avgRating: number | null;
            status: components["schemas"]["CycleStatus"];
            /** Format: date-time */
            closedAt: string | null;
        };
        TrainerScorecard: {
            trainer: components["schemas"]["TrainerListRow"];
            lifetime: {
                sessions: number;
                responses: number;
                avgRating: number;
                completionRate: number;
            };
            recentCycles: components["schemas"]["TrainerScorecardCycle"][];
            sentiment: components["schemas"]["SentimentBreakdown"];
        };
        /** @enum {string} */
        PersonStatus: "Active" | "Inactive";
        PersonRow: {
            /** Format: uuid */
            id: string;
            fullName: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["PersonStatus"];
            employeeCode?: string | null;
            /** Format: uuid */
            managerId?: string | null;
            managerName?: string | null;
            /** Format: date-time */
            lastActiveAt?: string | null;
        };
        PeoplePage: {
            data: components["schemas"]["PersonRow"][];
            page: number;
            pageSize: number;
            total: number;
        };
        /**
         * @description A single past or in-progress post-training feedback for the calling Maverick.
         *     `overallRating` and `submittedAt` are null while still a draft.
         */
        FeedbackHistoryItem: {
            /** Format: uuid */
            cycleId: string;
            courseName: string;
            trainerName?: string | null;
            /** Format: date-time */
            sessionEndedAt?: string | null;
            /** Format: date-time */
            dueAt: string;
            /** @enum {string} */
            status: "NotStarted" | "Draft" | "Submitted";
            overallRating?: number | null;
            /** Format: date-time */
            submittedAt?: string | null;
            cycleStatus?: components["schemas"]["CycleStatus"];
        };
        FeedbackHistoryPage: {
            data: components["schemas"]["FeedbackHistoryItem"][];
            page: number;
            pageSize: number;
            total: number;
        };
    };
    responses: {
        /** @description RFC 9457 problem+json error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        CycleIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "admin@hexaloop.dev",
                 *       "password": "demo"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "accessToken": "eyJhbGciOi...mock",
                     *       "refreshToken": "rt_01HF3K2P...mock",
                     *       "expiresInSeconds": 900,
                     *       "user": {
                     *         "id": "0192e9a8-2c1d-7a30-9c91-1f6f3a47b001",
                     *         "email": "admin@hexaloop.dev",
                     *         "fullName": "Alex Director",
                     *         "role": "Admin",
                     *         "employeeCode": "HX-0001",
                     *         "isActive": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description New access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: {
                /**
                 * @description Rolling time window the metrics, sentiment, and trainer scorecard are
                 *     computed over. Defaults to `90d`. Trend deltas always compare to the
                 *     immediately preceding window of the same length.
                 */
                window?: "30d" | "90d" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin dashboard payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboard"];
                };
            };
        };
    };
    getMaverickDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Maverick dashboard payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaverickDashboard"];
                };
            };
        };
    };
    getSupervisorDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supervisor dashboard payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupervisorDashboard"];
                };
            };
        };
    };
    getFeedbackForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Form bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackFormBundle"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    autosaveFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "overallRating": 4,
                 *       "highlights": "The labs were the highlight.",
                 *       "improvements": "Pacing felt rushed in module 2."
                 *     }
                 */
                "application/json": components["schemas"]["FeedbackDraftPatch"];
            };
        };
        responses: {
            /** @description Saved draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackDraft"];
                };
            };
            /** @description Submitted drafts cannot be modified */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                unreadOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications + unread count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated notification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent reports (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Report"][];
                    };
                };
            };
        };
    };
    triggerReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Queued / Ready (stub returns Ready immediately) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "messages": [
                 *         {
                 *           "role": "user",
                 *           "content": "Which cycle is at risk?"
                 *         }
                 *       ],
                 *       "context": {
                 *         "route": "/admin"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Assistant reply */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatReply"];
                };
            };
        };
    };
    listPendingEffectiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending items (and recent submissions) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectivenessQueue"];
                };
            };
        };
    };
    getEffectivenessForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
                maverickId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Form bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectivenessFormBundle"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    autosaveEffectiveness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
                maverickId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EffectivenessDraftPatch"];
            };
        };
        responses: {
            /** @description Saved draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectivenessDraft"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    submitEffectiveness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
                maverickId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EffectivenessSubmit"];
            };
        };
        responses: {
            /** @description Submitted response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectivenessDraft"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    listCycles: {
        parameters: {
            query?: {
                status?: "Open" | "Closed" | "OverrideClosed";
                type?: components["schemas"]["CycleType"];
                /** @description Free-text search across course name + trainer */
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated cycle list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CyclePage"];
                };
            };
        };
    };
    closeCycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cycle closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cycle"];
                };
            };
            /** @description Below threshold or already closed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemBelowThreshold"];
                };
            };
        };
    };
    overrideCloseCycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideCloseRequest"];
            };
        };
        responses: {
            /** @description Cycle override-closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cycle"];
                };
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listTrainers: {
        parameters: {
            query?: {
                /** @description Filter to Internal or External trainers */
                engagementType?: components["schemas"]["TrainerEngagementType"];
                /** @description Free-text match against the trainer's domain expertise */
                domain?: string;
                /** @description Free-text search across name + organization */
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated trainer directory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainerPage"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    getTrainerScorecard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scorecard with recent cycles + sentiment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainerScorecard"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listPeople: {
        parameters: {
            query?: {
                role?: components["schemas"]["Role"];
                status?: "Active" | "Inactive";
                /** @description Free-text search across name, email, employee code */
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated people directory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeoplePage"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    listFeedbackHistory: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submissions + drafts, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackHistoryPage"];
                };
            };
        };
    };
    submitFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSubmit"];
            };
        };
        responses: {
            /** @description Submitted feedback */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackDraft"];
                };
            };
            /** @description Cycle closed, threshold blocked, or draft incomplete */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
